version: '3'

services:

  nginx:
    build:
      context: ./minec_front/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./minec_front/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    command: ["nginx", "-g", "daemon off;"]

  backend:
    container_name: backend
    build:
      context: ./minec_back2/
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - ./minec_back2:/backend
    depends_on:
     - db


  db:
    image: postgres:10.1-alpine
    hostname: db
    environment:
      - POSTGRES_USER=michael
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=minec_base_3
    ports:
      - "5432:5432"
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data
