version: '3'

services:

  nginx:
    build:
      context: ./minec_front/
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./minec_front/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    command: ["nginx", "-g", "daemon off;"]

  backend:
    container_name: backend
    build:
      context: ./minec_back2/
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - ./minec_back2:/backend
      - /home/michael/sent_files:/home/michael/sent_files


  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

  celery-beat:
    container_name: celery_beat
    build:
      context: ./minec_back2/.
      dockerfile: celery-beat-Dockerfile
    depends_on:
      - backend
      - rabbit
    volumes:
      - ./data/:/data/
      - /home/michael/sent_files/:/home/michael/sent_files/
