# Generated by Django 2.1.7 on 2019-03-26 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('inn', models.IntegerField(primary_key=True, serialize=False, verbose_name='ИНН')),
                ('title', models.CharField(max_length=1000, verbose_name='название')),
            ],
        ),
        migrations.CreateModel(
            name='TaxBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='время добавления')),
                ('inn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbcontroller.Company')),
            ],
        ),
    ]
