# Generated by Django 2.1.7 on 2019-06-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alive',
            name='date_add_to_base',
        ),
        migrations.AddField(
            model_name='alive',
            name='disappear_factor',
            field=models.TextField(max_length=100, null=True, verbose_name='причина прекращения существования'),
        ),
        migrations.AlterField(
            model_name='scheduletable',
            name='type',
            field=models.TextField(choices=[(0, 'NONE'), (1, 'load'), (2, 'unzip'), (21, 'need_to_add'), (3, 'add'), (4, 'done')], default='NONE'),
        ),
    ]
