# Generated by Django 2.1.7 on 2019-06-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='federal_name',
            field=models.TextField(choices=[(0, 'Северо-Западный федеральный округ'), (1, 'Северо-Кавказский федеральный округ'), (2, 'Приволжский федеральный округ'), (3, 'Уральский федеральный округ'), (4, 'Центральный федеральный округ'), (5, 'Южный федеральный округ'), (6, 'Сибирский федеральный округ'), (7, 'Дальневосточный федеральный округ')], default='НЕИЗВЕСТНО', max_length=50, verbose_name='федеральный округ'),
        ),
    ]
