# Generated by Django 2.1.7 on 2019-03-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0002_auto_20190326_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxbase',
            name='data',
        ),
        migrations.AddField(
            model_name='company',
            name='date_create',
            field=models.DateField(null=True, verbose_name='дата создания компании'),
        ),
        migrations.AddField(
            model_name='taxbase',
            name='date_fns',
            field=models.DateField(null=True, verbose_name='время добавления ФНСом'),
        ),
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(max_length=1000, null=True, verbose_name='название'),
        ),
    ]
