# Generated by Django 2.1.7 on 2019-06-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0002_auto_20190617_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='okved',
            old_name='code',
            new_name='okved_code',
        ),
        migrations.RenameField(
            model_name='okved',
            old_name='code_name',
            new_name='okved_code_name',
        ),
        migrations.RenameField(
            model_name='okved',
            old_name='is_prime',
            new_name='okved_is_prime',
        ),
        migrations.AlterUniqueTogether(
            name='okved',
            unique_together={('okved_code', '_company')},
        ),
    ]
