# Generated by Django 2.1.7 on 2019-03-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0003_auto_20190327_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location_1_region',
            field=models.CharField(max_length=40, null=True, verbose_name='регион'),
        ),
        migrations.AddField(
            model_name='company',
            name='location_2_city',
            field=models.CharField(max_length=40, null=True, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='company',
            name='location_3_town',
            field=models.CharField(max_length=40, null=True, verbose_name='населенный пункт'),
        ),
        migrations.AddField(
            model_name='company',
            name='location_code',
            field=models.IntegerField(null=True, verbose_name='код региона'),
        ),
    ]
