# Generated by Django 2.1.7 on 2019-06-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0003_auto_20190617_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='company_category',
            field=models.TextField(choices=[(0, 'тип не определн'), (1, 'микропредприятие'), (2, 'малое предприятие'), (3, 'среднее предприятие')], default=0, max_length=20, verbose_name='категория компании'),
        ),
    ]
