# Generated by Django 2.1.7 on 2019-03-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0004_auto_20190328_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='location_1_region',
        ),
        migrations.RemoveField(
            model_name='company',
            name='location_2_city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='location_3_town',
        ),
        migrations.RemoveField(
            model_name='company',
            name='location_code',
        ),
        migrations.AddField(
            model_name='company',
            name='ГОРОД',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ГОРОДСКОЙ ОКРУГ',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Город',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ДАЧНЫЙ ПОСЕЛОК',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ДЕРЕВНЯ',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Деревня',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ЖЕЛЕЗНОДОРОЖНАЯ СТАНЦИЯ',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='КВАРТАЛ',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='КРАЙ',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ОБЛАСТЬ',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Область',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ПОСЕЛЕНИЕ',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ПОСЕЛОК',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ПОСЕЛОК ГОРОДСКОГО ТИПА',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Поселение',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Поселок',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='РАБОЧИЙ ПОСЕЛОК',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='РАЙОН',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='РЕСПУБЛИКА',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Рабочий поселок',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Район',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Республика',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='СЕЛО',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='СТАНЦИЯ',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Село',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
