# Generated by Django 2.1.7 on 2019-03-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0005_auto_20190328_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='ГОРОДСКОЙ ОКРУГ',
            new_name='район',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='ГОРОД',
            new_name='станция',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='Город',
            new_name='поселок городского типа',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='ДАЧНЫЙ ПОСЕЛОК',
            new_name='рабочий поселок',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='Деревня',
            new_name='село',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='Область',
            new_name='республика',
        ),
        migrations.RemoveField(
            model_name='company',
            name='ПОСЕЛОК ГОРОДСКОГО ТИПА',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Поселение',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Поселок',
        ),
        migrations.RemoveField(
            model_name='company',
            name='РАБОЧИЙ ПОСЕЛОК',
        ),
        migrations.RemoveField(
            model_name='company',
            name='РАЙОН',
        ),
        migrations.RemoveField(
            model_name='company',
            name='РЕСПУБЛИКА',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Рабочий поселок',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Район',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Республика',
        ),
        migrations.RemoveField(
            model_name='company',
            name='СЕЛО',
        ),
        migrations.RemoveField(
            model_name='company',
            name='СТАНЦИЯ',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Село',
        ),
        migrations.AddField(
            model_name='company',
            name='город',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='городской округ',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='дачный поселок',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
