# Generated by Django 2.1.7 on 2019-03-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0006_auto_20190328_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='ДЕРЕВНЯ',
            new_name='деревня',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='ЖЕЛЕЗНОДОРОЖНАЯ СТАНЦИЯ',
            new_name='железнодорожная станция',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='КВАРТАЛ',
            new_name='квартал',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='КРАЙ',
            new_name='край',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='ОБЛАСТЬ',
            new_name='область',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='ПОСЕЛЕНИЕ',
            new_name='поселение',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='ПОСЕЛОК',
            new_name='поселок',
        ),
        migrations.AddField(
            model_name='company',
            name='location_code',
            field=models.IntegerField(null=True, verbose_name='код региона'),
        ),
    ]
