# Generated by Django 2.1.7 on 2019-03-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0007_auto_20190328_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_ip',
            field=models.BooleanField(null=True, verbose_name='ИП'),
        ),
    ]
