# Generated by Django 2.1.7 on 2019-03-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0008_company_is_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='title_short',
            field=models.CharField(max_length=200, null=True, verbose_name='короткое название'),
        ),
    ]
