# Generated by Django 2.1.7 on 2019-04-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0009_company_title_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employee_num',
            field=models.IntegerField(null=True, verbose_name='количество работников'),
        ),
    ]
