# Generated by Django 2.1.7 on 2019-04-10 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0010_company_employee_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_num', models.IntegerField(null=True, verbose_name='количество работников')),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='employee_num',
        ),
        migrations.AddField(
            model_name='employeenum',
            name='inn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbcontroller.Company'),
        ),
    ]
