# Generated by Django 2.1.7 on 2019-04-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0011_auto_20190410_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeenum',
            name='inn',
        ),
        migrations.AddField(
            model_name='company',
            name='employee_num',
            field=models.IntegerField(null=True, verbose_name='количество работников'),
        ),
        migrations.DeleteModel(
            name='EmployeeNum',
        ),
    ]
