# Generated by Django 2.1.7 on 2019-04-11 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0012_auto_20190410_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('железнодорожная станция', models.CharField(max_length=40, null=True)),
                ('область', models.CharField(max_length=40, null=True)),
                ('поселок городского типа', models.CharField(max_length=40, null=True)),
                ('поселок', models.CharField(max_length=40, null=True)),
                ('район', models.CharField(max_length=40, null=True)),
                ('дачный поселок', models.CharField(max_length=40, null=True)),
                ('край', models.CharField(max_length=40, null=True)),
                ('городской округ', models.CharField(max_length=40, null=True)),
                ('станция', models.CharField(max_length=40, null=True)),
                ('село', models.CharField(max_length=40, null=True)),
                ('квартал', models.CharField(max_length=40, null=True)),
                ('деревня', models.CharField(max_length=40, null=True)),
                ('республика', models.CharField(max_length=40, null=True)),
                ('поселение', models.CharField(max_length=40, null=True)),
                ('рабочий поселок', models.CharField(max_length=40, null=True)),
                ('город', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_num', models.IntegerField(null=True, verbose_name='количество работников')),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='employee_num',
        ),
        migrations.RemoveField(
            model_name='company',
            name='title',
        ),
        migrations.RemoveField(
            model_name='company',
            name='title_short',
        ),
        migrations.RemoveField(
            model_name='company',
            name='город',
        ),
        migrations.RemoveField(
            model_name='company',
            name='городской округ',
        ),
        migrations.RemoveField(
            model_name='company',
            name='дачный поселок',
        ),
        migrations.RemoveField(
            model_name='company',
            name='деревня',
        ),
        migrations.RemoveField(
            model_name='company',
            name='железнодорожная станция',
        ),
        migrations.RemoveField(
            model_name='company',
            name='квартал',
        ),
        migrations.RemoveField(
            model_name='company',
            name='край',
        ),
        migrations.RemoveField(
            model_name='company',
            name='область',
        ),
        migrations.RemoveField(
            model_name='company',
            name='поселение',
        ),
        migrations.RemoveField(
            model_name='company',
            name='поселок',
        ),
        migrations.RemoveField(
            model_name='company',
            name='поселок городского типа',
        ),
        migrations.RemoveField(
            model_name='company',
            name='рабочий поселок',
        ),
        migrations.RemoveField(
            model_name='company',
            name='район',
        ),
        migrations.RemoveField(
            model_name='company',
            name='республика',
        ),
        migrations.RemoveField(
            model_name='company',
            name='село',
        ),
        migrations.RemoveField(
            model_name='company',
            name='станция',
        ),
        migrations.AddField(
            model_name='company',
            name='still_alive',
            field=models.BooleanField(default=True, verbose_name='еще существует?'),
        ),
        migrations.AddField(
            model_name='employeenum',
            name='inn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbcontroller.Company'),
        ),
        migrations.AddField(
            model_name='companylocation',
            name='inn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbcontroller.Company'),
        ),
    ]
