# Generated by Django 2.1.7 on 2019-04-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0013_auto_20190411_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxbase',
            name='Акцизы, всего',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='taxbase',
            name='Водный налог',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='taxbase',
            name='Единый налог на вмененный доход для отдельных видов  деятельности',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='taxbase',
            name='Единый сельскохозяйственный налог',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='taxbase',
            name='Задолженность и перерасчеты по ОТМЕНЕННЫМ НАЛОГАМ  и сборам и иным обязательным платежам  (кроме ЕСН, страх. Взносов)',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='taxbase',
            name='Земельный налог',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='taxbase',
            name='НЕНАЛОГОВЫЕ ДОХОДЫ, администрируемые налоговыми органами',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='taxbase',
            name='Налог на добавленную стоимость',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='taxbase',
            name='Налог на добычу полезных ископаемых',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='taxbase',
            name='Налог на доходы физических лиц',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='taxbase',
            name='Налог на имущество организаций',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='taxbase',
            name='Налог на прибыль',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='taxbase',
            name='Налог, взимаемый в связи с  применением упрощенной  системы налогообложения',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='taxbase',
            name='Сборы за пользование объектами животного мира  и за пользование объектами ВБР',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='taxbase',
            name='Страховые взносы на обязательное медицинское страхование работающего населения, зачисляемые в бюджет Федерального фонда обязательного медицинского страхования',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='taxbase',
            name='Страховые взносы на обязательное социальное страхование на случай временной нетрудоспособности и в связи с материнством',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='taxbase',
            name='Страховые и другие взносы на обязательное пенсионное страхование, зачисляемые в Пенсионный фонд Российской Федерации',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='taxbase',
            name='Торговый сбор',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='taxbase',
            name='Транспортный налог',
            field=models.FloatField(default=0),
        ),
    ]
