# Generated by Django 2.1.7 on 2019-05-13 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0014_auto_20190412_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_ip',
            field=models.BooleanField(null=True, verbose_name='является ИП'),
        ),
        migrations.AlterField(
            model_name='companylocation',
            name='inn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dbcontroller.Company'),
        ),
        migrations.AlterField(
            model_name='employeenum',
            name='inn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dbcontroller.Company'),
        ),
    ]
