# Generated by Django 2.1.7 on 2019-05-16 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0015_auto_20190513_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxbase',
            name='inn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dbcontroller.Company'),
        ),
    ]
