# Generated by Django 2.1.7 on 2019-05-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0016_auto_20190516_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxbase',
            name='date_fns',
            field=models.DateField(null=True, verbose_name='время добавления ФНСом информации о налогах'),
        ),
    ]
