# Generated by Django 2.1.7 on 2019-05-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0018_auto_20190516_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companylocation',
            name='inn',
        ),
        migrations.DeleteModel(
            name='CompanyLocation',
        ),
    ]
