# Generated by Django 2.1.7 on 2019-05-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0020_auto_20190521_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='alive',
            name='life_duration_years',
            field=models.IntegerField(default=-1, verbose_name='продолжительность существования (лет)'),
        ),
        migrations.AlterField(
            model_name='alive',
            name='date_created',
            field=models.DateField(verbose_name='дата добавления в базу'),
        ),
    ]
