# Generated by Django 2.1.7 on 2019-05-21 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0022_auto_20190521_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(verbose_name='доход')),
                ('outcome', models.IntegerField(verbose_name='расход')),
                ('inn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dbcontroller.Company')),
            ],
        ),
    ]
