# Generated by Django 2.1.7 on 2019-05-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0023_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income',
            field=models.FloatField(verbose_name='доход'),
        ),
        migrations.AlterField(
            model_name='income',
            name='outcome',
            field=models.FloatField(verbose_name='расход'),
        ),
    ]
