# Generated by Django 2.1.7 on 2019-05-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcontroller', '0025_auto_20190521_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alive',
            old_name='date_created',
            new_name='date_add_to_base',
        ),
        migrations.RemoveField(
            model_name='company',
            name='date_create',
        ),
        migrations.AddField(
            model_name='alive',
            name='date_create',
            field=models.DateField(null=True, verbose_name='дата создания компании'),
        ),
    ]
